### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by RobertoGraham** [corretto/corretto-8-docker#13]
Could this be made available on Docker Hub? I think it would be quite straightforward to set up an Automated Build repository over there that builds from this repository

**Comment by EricEdens** [comment]
Thanks Roberto! Although we don't have a set date, we're busy onboarding with Docker Hub. Stay tuned for updates within this thread.

**Comment by EricEdens** [comment]
Here are the PRs that we've staged to onboard to Docker Hub:
 - https://github.com/docker-library/docs/pull/1369
 - https://github.com/docker-library/official-images/pull/5113

**Comment by hoegertn** [comment]
https://hub.docker.com/_/amazoncorretto
