### ISSUE TITLE
Update Dockerfile to 8.202.08.2

### ISSUE THREAD

**Issue by aantono** [corretto/corretto-8-docker#19]
The current Dockerfile builds 8.202.08.1 while 8.202.08.2 has been released later the same day, but not reflected in the Dockerfile.

**Comment by davecurrie** [comment]
@aantono The two builds will run the same, with this commit (setting java.vm.vendor property) being the only difference https://github.com/corretto/corretto-8/commit/5cf540cf814dd5e29e32595a4f2f1760cfedba41

This patch will make it into AL2 during the next few days, and by extension into the Dockerfile. Please let us know if this causes you any issues.

**Comment by aantono** [comment]
I think if its only going to be a few days, we can wait... We just wanted to actually take advantage of the proper markers in the vendor property to be able to see which VM is running... ;)
