### ISSUE TITLE
Remove has binary files and weights 76.71MB

### ISSUE THREAD

**Issue by Mart-Bogdan** [corretto/corretto-8-docker#2]
Remove binary files from history.
Despite being delted git clone takes 76 Mb 
```
>docker build -t amazon-corretto-8 github.com/corretto/corretto-8-docker
Sending build context to Docker daemon  76.71MB
Step 1/3 : FROM amazonlinux:2
```

consider using force-push from **new** local repo, or use tool like filter-branch, `rebase -i` or BFG to remove binary bloat

**Comment by EricEdens** [comment]
Good catch, @Mart-Bogdan! I'm fine removing the RPMs after YUM finishes installing them.

**Comment by nbihan-mediware** [comment]
@EricEdens, that is a good fix but not related to the issue. This issue was about removing binaries from the repo so it is not that big.
