### ISSUE TITLE
JAVA_HOME missing on amazoncorretto:8 images

### ISSUE THREAD

**Issue by alissonsales** [corretto/corretto-8-docker#27]
See https://github.com/docker-library/repo-info/blob/master/repos/amazoncorretto/local/8.md

```
$ docker run --rm amazoncorretto:8 printenv
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=05cbf6b80a21
HOME=/root
```

```
$ docker run --rm amazoncorretto:11 printenv
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=c56b19925283
JAVA_HOME=/usr/lib/jvm/java-11-amazon-corretto
HOME=/root
```

**Comment by EricEdens** [comment]
@mattnelson added this in #20, and it'll go out in our next update.

In the meantime, if you need the value, you can set it as shown here: https://github.com/corretto/corretto-8-docker/blob/master/Dockerfile
