### ISSUE TITLE
JAVA_HOME seems to be incorrect

### ISSUE THREAD

**Issue by nikarh** [corretto/corretto-8-docker#31]
JAVA_HOME currently points to `/usr/lib/jvm/java-1.8.0-amazon-corretto.x86_64`, but JVM actually resides in `/usr/lib/jvm/java-1.8.0-amazon-corretto`:

```sh
sh-4.2# echo $JAVA_HOME
/usr/lib/jvm/java-1.8.0-amazon-corretto.x86_64

sh-4.2# ls $JAVA_HOME
ls: cannot access /usr/lib/jvm/java-1.8.0-amazon-corretto.x86_64: No such file or directory

sh-4.2# ls /usr/lib/jvm/java-1.8.0-amazon-corretto
ASSEMBLY_EXCEPTION  LICENSE  THIRD_PARTY_README  bin  include  javafx-src.zip  jre  lib  man  src.zip  version.txt
```

**Comment by EricEdens** [comment]
Thanks for the report! Taking a look ...

**Comment by EricEdens** [comment]
Good find! I'm updating the `8-al2-full` branch now. It looks like https://github.com/corretto/corretto-8-docker/pull/32  addresses `master`.

**Comment by EricEdens** [comment]
Fixed by https://github.com/corretto/corretto-8-docker/commit/055b9f36817325fbf5d2469150684ad8a4f4f1e4
