### ISSUE TITLE
Non-root user?

### ISSUE THREAD

**Issue by adaniline-traderev** [corretto/corretto-8-docker#34]
How can I add a user to my image, if I don't want to runn the app as root?

**Comment by EricEdens** [comment]
Hey @adaniline-traderev  -- it sounds like you're looking for the [USER](https://docs.docker.com/engine/reference/builder/#user) instruction.

I'm going to go ahead and close this since you also have some responses in the amazonlinux repo: https://github.com/amazonlinux/container-images/issues/28 .

**Comment by adaniline-traderev** [comment]
Thank you, this answered my question
