### ISSUE TITLE
aarch64 Docker image around the corner?

### ISSUE THREAD

**Issue by gregorkistler** [corretto/corretto-8-docker#38]
Hi,

I've noticed that you provide some pre-release packages of Corretto 8 via https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html also for aarch64.

Just wanted to ask if we will see official images in Docker Hub within the next weeks or months?

Thank you.

**Comment by davecurrie** [comment]
Hi.

Corretto aarch64 images will be available before Corretto on aarch64 is GA. The timeline isn't fixed but we're expecting it to happen soon.

**Comment by davecurrie** [comment]
Also, @gregorkistler, if you're using our aarch64 builds we're very interested to hear your feedback. Is it working as expected for you?

**Comment by gregorkistler** [comment]
Hi Dave,

great, thank you :)
Well in this case I'm just an end-user. I don't use it for development purposes but so far I have no issues with it.
Mainly used in conjunction with Play! framework 1.x and different Tomcat versions.
