### ISSUE TITLE
Behind corporate proxy I am not able to download the java rpm through curl command

### ISSUE THREAD

**Issue by skpandey91** [corretto/corretto-8-docker#42]
Hi I am trying to build the amazon corretto image based on the docker file for correttot-8-docker.
But I am getting below error.

[INFO] DOCKER> [91mcurl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to my.proxy

It is not able to download the java rpm through corporate proxy

**Comment by davecurrie** [comment]
Hi @skpandey91.

You may need to customize the dockerfile to work in your specific environment. Have you already made a change that doesn't work as expected?

**Comment by skpandey91** [comment]
After setting correct proxy setting I am able to download it.
@davecurrie Thanks!!!
