### ISSUE TITLE
Tags for 8 and latest did not get updated with latest release of 8u232

### ISSUE THREAD

**Issue by albuch** [corretto/corretto-8-docker#44]
Hi,
we're seeing that `amazoncorretto:8u232` was released a couple of hours ago to docker hub (https://hub.docker.com/_/amazoncorretto?tab=tags) but `amazoncorretto:8` and `amazoncorretto:latest` we're not updated accordingly and still are on 8u222.

Same is true for `amazoncorretto:11`

This is not what I would expect from these tags. Is there something wrong in the publishing pipeline?

**Comment by cliveverghese** [comment]
Hi @albuch , 

Thank you for reporting this issue.

We are looking into getting this fixed.

**Comment by cliveverghese** [comment]
Hi @albuch ,

The issues with docker hub have been resolved. The tags amazoncorretto:8 and amazoncorretto:11 now use versions 8u232 and 11.0.5 respectively.

Closing this issue. Kindly reopen if problem persists.
