### ISSUE TITLE
Publish corretto debian image

### ISSUE THREAD

**Issue by sushant-pradhan** [corretto/corretto-8-docker#61]
Hello,

I see that there is a debian flavor under contrib/debian/Dockerfile but do not see the docker image in dockerhub. Can the debian image be published as well to dockerhub?

Thanks,
An

**Comment by duncaan** [comment]
They do not plan on supporting it: https://github.com/docker-library/official-images/pull/6886#issuecomment-561400888

**Comment by davecurrie** [comment]
We'll take note of this request, thanks for opening it.
